//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compiler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compiler.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space a{
        ///	class A{
        ///		function void Abs(int s){
        ///			M=M[A,B,C,&quot;&quot;,3];
        ///
        ///			sA=A+B+C*D^2+F*Z;
        ///			L=0+1+2+3+4+5+6+7+8+9;
        ///			int b=Abs(halt(s,d));
        ///			double r;
        ///			r=doubl(A);
        ///			if(s&lt;0)b=-s;
        ///			return b;
        ///		}		
        ///		function int pow(int a,int b){
        ///			return Math.Pow(a,b);
        ///		}	
        ///	}	
        ///	space a{
        ///		class A{
        ///			function void Abs(int s){
        ///				M=M[ACHOUR,ADOUD+BSOUE+CAZSD*MACHOUR[A,B,C,&quot;&quot;,3]^2+F*Z,C,&quot;&quot;,3];
        ///				sA=A+B+C*M[A,B,C,&quot;&quot;,3]^2+F*Z;
        ///				L=0+1+2+3+4+5+6+7+8+9;
        ///				int b=Abs(halt(s,d));
        ///				double r; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prg {
            get {
                return ResourceManager.GetString("Prg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      
        ///      space a{
        ///        class A{
        ///          function void Abs(int s){
        ///            M=M[ACHOUR,ADOUD+BSOUE+CAZSD*MACHOUR[A,B,C,&quot;&quot;,3]+2+F*Z,C,&quot;&quot;,((((3+A*V-C-2*2))))];
        ///          }
        ///        }
        ///      }
        ///    .
        /// </summary>
        internal static string Prg1 {
            get {
                return ResourceManager.GetString("Prg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space a{
        ///	class A{
        ///		function void Abs(int s){
        ///			M=M[A,B,C,&quot;&quot;,3];
        ///
        ///			sA=A+B+C*D^2+F*Z;
        ///			L=0+1+2+3+4+5+6+7+8+9;
        ///			int b=Abs(halt(s,d));
        ///			double r;
        ///			r=doubl(A);
        ///			if(s&lt;0)b=-s;
        ///			return b;
        ///		}		
        ///		function int pow(int a,int b){
        ///			if(a&gt;b)
        ///				return Math.Pow(a,b);
        ///			else
        ///				return Math.Pow(a,-b);
        ///		}	
        ///	}
        ///}.
        /// </summary>
        internal static string SE {
            get {
                return ResourceManager.GetString("SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space.
        /// </summary>
        internal static string space {
            get {
                return ResourceManager.GetString("space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
